### ISSUE TITLE
Request: call the library as something else

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Danylo2006/LondonEyeLayoutManager#2]
Maybe "circularLayoutManager" , or "ArcLayoutManager".
"London" doesn't say anything about it being in this shape...

**Comment by danylovolokh** [comment]
It says "London Eye", but I get your point. I will consider that. Thanks :)

**Comment by AndroidDeveloperLB** [comment]
Oh, sorry. And now I know why it's called this way, like the giant Ferris wheel (sorry English isn't my main language)
